export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_ERROR = 'GET_TICKETS_ERROR';
export const GET_TICKETS_PENDING = 'GET_TICKETS_PENDING';
export const PATCH_SOMOIM_SUCCESS = 'PATCH_SOMOIM_SUCCESS';
export const PATCH_SOMOIM_ERROR = 'PATCH_SOMOIM_ERROR';
export const PATCH_SOMOIM_PENDING = 'PATCH_SOMOIM_PENDING';
