export const MESSAGE_VALIDATION_SUCCESS = 'MESSAGE_VALIDATION_SUCCESS';
export const MESSAGE_VALIDATION_ERROR = 'MESSAGE_VALIDATION_ERROR';
export const MESSAGE_VALIDATION_PENDING = 'MESSAGE_VALIDATION_PENDING';
