export const GET_TICKETINGAVAIL_SUCCESS = 'GET_TICKETINGAVAIL_SUCCESS';
export const GET_TICKETINGAVAIL_ERROR = 'GET_TICKETINGAVAIL_ERROR';
export const GET_TICKETINGAVAIL_PENDING = 'GET_TICKETINGAVAIL_PENDING';
